### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by afocus** [oskca/sciter#1]
import the path of the old. `github.com/datagoes/sciter`
Examples of the download in win10 seems to have problems , directly out of the middle somewhere .

**Comment by oskca** [comment]
Thanks for your report.

The import path of sciter in `download example` should be `github.com/oskca/sciter`  :), But I don't know your problems exactly, would put your stack strace here? 

BTW: the example program takes a sciter compatible page url to work properly, which means that a html page with css or tiscript would work but not with javascript.

**Comment by afocus** [comment]
thk for your reply.
