### ISSUE TITLE
NthAttr(int) returning the attr name.

### ISSUE THREAD

**Issue by josephbudd** [oskca/sciter#11]
**The problem is that NthAttr(int) is not returning the value but the name.
See the end of this post for the correction to sciter.go**

print out:

2015/12/29 21:17:58 el.NthAttrName(0) is "id"
2015/12/29 21:17:58 el.NthAttr(0) is "id"
2015/12/29 21:17:58 el.NthAttrName(1) is "itemid"
2015/12/29 21:17:58 el.NthAttr(1) is "itemid"

code snipet
```
		name, err := el.NthAttrName(i)
		if err != nil {
			log.Printf("el.NthAttrName() error is %q", err.Error())
			return "", err
		}
        log.Printf("el.NthAttrName(%d) is %q", i, name)
        value, err := el.NthAttr(i)
        if err != nil {
            log.Printf("el.NthAttr(i) error is %q", err.Error())
            return "", err
        } else {
            log.Printf("el.NthAttr(%d) is %q", i, value)
        }

```

also el.Attr(string) panics with index out of bounds.

**Here is the fix for NthAttr that i made to sciter.go:**
lines 752 & 753 are commented out and the proper two lines are below them
```
	//r := C.SciterGetNthAttributeNameCB(e.handle, cn, lpcstr_receiver, cparam)
	//err = wrapDomResult(r, "SciterGetNthAttributeNameCB")
	r := C.SciterGetNthAttributeValueCB(e.handle, cn, lpcwstr_receiver, cparam)
	err = wrapDomResult(r, "SciterGetNthAttributeValueCB")

```

**Comment by oskca** [comment]
fixed by #12
