### ISSUE TITLE
After setHTML can't find id anymore to clear or change content

### ISSUE THREAD

**Issue by gcstang** [oskca/sciter#120]
Latest version of Sciter and Go as well as go-sciter.

RRO[0002] SelectFirst:no proper element found 

`Set Content (works properly)
err := content.SetHtml(pg, sciter.SOH_REPLACE)

In the new content I have other html fields with ID's but they can't be found.
Also if I try to clear the content I set earlier I get the error as shown above 'no proper element found'
`

**Comment by pravic** [comment]
cc @c-smile

**Comment by c-smile** [comment]
How do you call `SelectFirst` ?  For what element? If for the same `content` element then 
`SOH_REPLACE` removes the content element from the DOM - replaces it by that html. So content is dead after the call. You should use `SIH_REPLACE_CONTENT` modifier if you want to preserve the element itself and just replace its content.

**Comment by gcstang** [comment]
thank you, I'll try that.
what about finding id's in the content i put in it's place is that not
available to the native side?  do i have to do something to register those
elements and id's?

**Comment by c-smile** [comment]
Did you try `child = content.SelectFirst("#thatid")` ?

**Comment by gcstang** [comment]
i just tried by id on root, I'll try it this way instead.

thank you

**Comment by gcstang** [comment]
@c-smile is there a way to load the tis pages dynamically also?
The tips you sent me are working perfectly but the new content has a separate page for js functions in it's own tis file.  This is my first time working with this API and want to make sure I'm doing it properly.  
I have a:
1. starting page that has a ui.tis (basically just centers the window on the screen), a button loads a search form, that form has buttons which are activated with the search.tis for callbacks and such. 
2. results table that would have a next/prev (basically going to display 1~n images that will allow deletion of duplicates, each set of results will be a single set of duplicates on a file set. This will most likely also have it's own tis file.
