### ISSUE TITLE
Unhandle Event HANDLE_DRAW cause panic in windows 10

### ISSUE THREAD

**Issue by mikeshimura** [oskca/sciter#14]
I run examples handlers program and followings are log.

2016/02/05 14:02:18 Unhandled sciter event case: 64
panic: Unhandled sciter event case: 64

goroutine 1 [running, locked to thread]:
log.Panic(0xc082071a88, 0x2, 0x2)
	c:/go/src/log/log.go:320 +0xc8
github.com/oskca/sciter.goElementEventProc(0xc08244a230, 0x16eca80, 0x40, 0xfff248, 0x0)
	D:/AW/networks/wknetworks/netsample/src/github.com/oskca/sciter/sciter.go:1324 +0x57b

I comment out following line and process normal.

//log.Panic("Unhandled sciter event case: ", evtg)

Masanobu Shimura

**Comment by josephbudd** [comment]
I added this line before default.

    case HANDLE_DRAW:

**Comment by oskca** [comment]
fixed by #12
