### ISSUE TITLE
Usage of NthElementKey

### ISSUE THREAD

**Issue by everplus** [oskca/sciter#17]
I want to enumerate the javascript object keys. Can I use NthElementKey?
I try to use it, but failed, got nil.

Can anyone give me some help.

```
{
	"string":"hello",
	"number":123
}
```

I want to get "string" and "number", thanks

**Comment by oskca** [comment]
This has to be done with sciter API  `ValueEnumElements`, but it's not wrapped yet. I'll do it late this day :)

**Comment by everplus** [comment]
Thank you very much

**Comment by oskca** [comment]
And the `Value.Isolate` which converts the object to a T_MAP or a T_ARRAY can be combined with `NthElementKey` to achieve your goals according to https://github.com/c-smile/sciter-sdk/issues/22#issuecomment-189800524 :smile:
