### ISSUE TITLE
panic: runtime error: cgo argument has Go pointer to Go pointer

### ISSUE THREAD

**Issue by josephbudd** [oskca/sciter#18]
Is anyone else still getting this error? Not sure if it is caused by the sciter lib or if i broke some tiscript that I was adding while waiting for lib fixes.

I just updated the sciter lib using $ go get -u -x github.com/oskca/sciter
Then I rebuilt my app with go build.
Then I ran the app.

**The second line in my code ( shown  below ) generates the fatal.**
`
 fnvalue := sciter.NewValue()

 fnvalue.SetNativeFunctor(myMenuHandlerFunc)
`

**Here is the fatal.**

panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running, locked to thread]:
panic(0x5c89c0, 0xc0820035c0)
        C:/Go/src/runtime/panic.go:464 +0x3f4
github.com/oskca/sciter._cgoCheckPointer0(0x585ee0, 0xc082020050, 0x0, 0x0, 0x0, 0x1)
        ??:0 +0x54
github.com/oskca/sciter.(*Value).SetNativeFunctor(0xc0820035b0, 0xc082074cc0, 0x0, 0x0)
        C:/Users/user1/MyProjects/go/src/github.com/oskca/sciter/sciter.go:2242 +0xf4

**Comment by oskca** [comment]
Well, it's strange, the [`handler`](https://github.com/oskca/sciter/blob/master/examples/handlers/handlers.go#L22) example works fine on my platform: `windows 10 amd64`. 

Have you tried the [`handler`](https://github.com/oskca/sciter/blob/master/examples/handlers/handlers.go#L22) example？

**Comment by josephbudd** [comment]
no i'll do that thankyou.

**Comment by josephbudd** [comment]
I'm not as rushed today as i was the other day. I see that the handler example does not use sciter.SetNativeFunctor.

I studied the examples a long time ago and used them to write my code. However, I have 16 calls to sciter.SetNativeFunctor in my code.

**Comment by oskca** [comment]
[`handler example line 22`](https://github.com/oskca/sciter/blob/master/examples/handlers/handlers.go#L22) call `sciter.NewValue(fn)` which calls `sciter.SetNativeFunctor` [indirectly](https://github.com/oskca/sciter/blob/master/value.go#L108) 

While the  [`handler`](https://github.com/oskca/sciter/blob/master/examples/handlers/handlers.go#L22) works, do you still get this error for your own code?

**Comment by josephbudd** [comment]
Yes, I just modified my code to use use sciter.NewValue(fn) and I still get the error at the line with sciter.NewValue(fn).

**Comment by josephbudd** [comment]
I wrote a much smaller app and .SetNativeFunctor works perfectly.

**Comment by josephbudd** [comment]
.SetNativeFunctor does not work with closures. Its only with closures that i get the panic.

**Comment by josephbudd** [comment]
.SetNativeFunctor does work with closures.

```go
    nativefunctorclosure := func(args ...*sciter.Value) *sciter.Value {
        log.Printf(" in nativefunctorclosure GoOnClickHandler: #args is %d\n", len(args))
        return sciter.NullValue()
    }
    v := sciter.NewValue()
    v.SetNativeFunctor(sciter.NativeFunctor(nativefunctorclosure))
```
