### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by sebastianmacias** [oskca/sciter#2]
Hi, it would be very helpful to have a getting started guide. I see the samples folder but couldn't find information about setting up the sciter-sdk-3.

Thanks

**Comment by oskca** [comment]
Yeah! That would be nice.

I've added a [Getting Started](https://github.com/oskca/sciter#getting-started) section in readme :smile:

**Comment by sebastianmacias** [comment]
Thanks, I'll check it out.
