### ISSUE TITLE
error in func (e *Element) SetText(text string) 

### ISSUE THREAD

**Issue by c-smile** [oskca/sciter#27]
Here:
```
func (e *Element) SetText(text string) error {
	// args
	ctext := C.LPCWSTR(StringToWcharPtr(text))
	clength := C.UINT(len(text))
	// cgo call
	r := C.SciterSetElementText(e.handle, ctext, clength)
	return wrapDomResult(r, "SciterSetElementText")
}
```
wrong string length is passed to SciterSetElementText function. 

SciterSetElementText expects ctext length -  number of UTF16 code units in that ctext.
But in the code above clength is a number of characters (what are they in go?)  in text.

**Comment by coolit** [comment]
You are right.
I think it should be:
clength := C.UINT(len([]rune(text)))

**Comment by c-smile** [comment]
Yet other similar places need to be examined too.

**Comment by oskca** [comment]
Sorry for the late reply for I'm being busy recently and I should look into this in the weekend!

**Comment by coolit** [comment]
awesome, welcomeback
