### ISSUE TITLE
How to set window title icon

### ISSUE THREAD

**Issue by Archieeeeee** [oskca/sciter#32]
I do not find a method to set  an icon for a window and it seems sciter does not implement that, now I have tried to add an icon for the built file but still when running the default icon is shown on the title, I want to know is there an approach to make that in Go, thanks

**Comment by oskca** [comment]
icon for GUI window is not done in sciter but in platform specific APIs. 

The proper place to implements `SetWindowIcon` is `window_windows.go window_linux.go or window_darwin.go'. But there's no plan to implement them right now :)

**Comment by ffred60** [comment]
didn't tried yet, but seems [here](https://sciter.com/tag/window/) that it's possible.

**Comment by pravic** [comment]
> `view.windowIcon = null | "url" | Image; ` – set window icon programmatically. See: sdk/samples.dialogs+windows/window-icon.htm
`<html window-icon="url">` html property for the same purpose.

**Comment by jilieryuyi** [comment]
> > `view.windowIcon = null | "url" | Image; ` – set window icon programmatically. See: sdk/samples.dialogs+windows/window-icon.htm
> > `<html window-icon="url">` html property for the same purpose.

not work for me
