### ISSUE TITLE
 fatal error: sciter-x.h: No such file or directory

### ISSUE THREAD

**Issue by lysShub** [oskca/sciter#338]
```
# github.com/sciter-sdk/go-sciter
vendor\github.com\sciter-sdk\go-sciter\sciter.go:12:10: fatal error: sciter-x.h: No such file or directory
 #include "sciter-x.h"
          ^~~~~~~~~~~~
compilation terminated.
```

when i run examples/callback demo.

And I found [issue 297](https://github.com/sciter-sdk/go-sciter/issues/297)， but I don't know what can I do?

**Comment by lysShub** [comment]
gomod  will not load include dir to vendor/github.com/sciter-sdk/go-sciter

**Comment by LycEcho** [comment]
how do it
