### ISSUE TITLE
Exception 0xc0000005 0x8 0x0 0x0

### ISSUE THREAD

**Issue by OnePlusOne-Code** [oskca/sciter#340]
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0
signal arrived during external code execution

runtime.cgocall(0x7ff66e674610, 0xc00007de38)
        D:/golang/www/src/runtime/cgocall.go:157 +0x4a fp=0xc00007de10 sp=0xc00007ddd8 pc=0x7ff66e5c384a
github.com/sciter-sdk/go-sciter._Cfunc_SciterCreateWindow(0x296, 0x7ff66e689820, 0x7ff66e620e0a, 0x0, 0x0)

        _cgo_gotypes.go:489 +0x5b fp=0xc00007de38 sp=0xc00007de10 pc=0x7ff66e66dbdb
github.com/sciter-sdk/go-sciter.CreateWindow.func1(0x30?, 0x0?, 0x30?, 0x6?, 0x0?)
        D:/GOPATH/bin/test/main.go:18 +0x25 fp=0xc00007df80 sp=0xc00007df40 pc=0007dfe0 pc=0x7ff66e61da0100007df40 sp=0xc00007ded8 pc=0x7ff66e6723f1
rax     0x0xit()r-sdk/go-sciter/window.New(0x296, 0x7ff66e67d480?)
rbx     0xc00007de38w/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00007dfe8 sp=0xc00go:51 +0x79 fp=0xc00007dea0 sp=0xc00007de38 pc=0x7ff66e6708b9
rcx     0x296iter-sdk/go-sciter.CreateWindow(0x6e6b3b80?, 0x7ff66e6d0b98?, 0x7ff66e5fe385?, 0xc000042000?, 0x300000002?)
rdi     0xc00007e000
rsi     0x7ff66e76a7a0
rbp     0xc00007de00
rsp     0x45db7ff6c8
r8      0x7ff66e620e0a
r9      0x0
r10     0x0
r11     0x45db7ff350
r12     0xc000020000
r13     0xc000020000
r14     0xc000042000
r15     0x2
rip     0x0
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b

**Comment by OnePlusOne-Code** [comment]
Hi, may I ask how to solve this situation?

**Comment by justinsantoro** [comment]
the solution is to get the most recent version from the master branch:

`go get github.com/sciter-sdk/go-sciter@master`

see #297

**Comment by OnePlusOne-Code** [comment]
@justinsantoro Thank you!
