### ISSUE TITLE
windows 10 build error

### ISSUE THREAD

**Issue by josephbudd** [oskca/sciter#4]
**go get -x github.com/oskca/sciter**
WORK=C:\Users\user1\AppData\Local\Temp\go-build053903754
mkdir -p $WORK\github.com\oskca\sciter\_obj\
mkdir -p $WORK\github.com\oskca\
cd C:\Users\user1\My Projects\go\src\github.com\oskca\sciter
CGO_LDFLAGS="-g" "-O2" "C:\\Go\\pkg\\tool\\windows_amd64\\cgo.exe" -objdir "C:\\Users\\user1\\AppData\\Local\\Temp\\go-build053903754\\github.com\\oskca\\sciter\\_obj\\" -importpath github.com/oskca/sciter -- -I "C:\\Users\\user1\\AppData\\Local\\Temp\\go-build053903754\\github.com\\oskca\\sciter\\_obj\\" -g -w -std=c11 -Iinclude -Iinclude -Iinclude sciter.go sciter_windows.go types.go utils.go
\# github.com/oskca/sciter
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

**gcc --version**
gcc (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 5.2.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**I also get this cc1.exe error with "go build".**

**Comment by oskca** [comment]
According to the message `cc1.exe: sorry, unimplemented: 64-bit mode not compiled in` and your 
`gcc --version` output:
```
gcc (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 5.2.0
```

It seems that yor're using `golang amd64` and `gcc i386` together.  Try using the 64 bit version of `Mingw-W64` and see what happens. :smile:

**Comment by josephbudd** [comment]
I thought i had the 64 bit version. I got it from here.
If that's not the 64 bit version, where do i get it from?

**Comment by josephbudd** [comment]
Thank you, I figured out how to install the 64 bit version.
