### ISSUE TITLE
handlers example : no html file found

### ISSUE THREAD

**Issue by poshu** [oskca/sciter#9]
Keep in mind that I'm very new to go (like... 30 minutes new).
I installed everything, it did work, I successfully tested the simple example, but I have no success with handlers : I always get a "no html file found" error.
It probably got to do with rice though, does anyone has a lead to where I should start looking?

**Comment by oskca** [comment]
the handlers example needs an argument to function correclty 

the correct form is : `handler.exe a.html`

**Comment by poshu** [comment]
Thanks.
